import { Letter } from './letter'

// 清音
export const seions: Letter[] = [
  { hiragana: 'あ', katakana: 'ア', roomaji: 'a', chinese: '安' },
  { hiragana: 'い', katakana: 'イ', roomaji: 'i', chinese: '以' },
  { hiragana: 'う', katakana: 'ウ', roomaji: 'u', chinese: '宇' },
  { hiragana: 'え', katakana: 'エ', roomaji: 'e', chinese: '衣' },
  { hiragana: 'お', katakana: 'オ', roomaji: 'o', chinese: '於' },
  { hiragana: 'か', katakana: 'カ', roomaji: 'ka', chinese: '加' },
  { hiragana: 'き', katakana: 'キ', roomaji: 'ki', chinese: '幾' },
  { hiragana: 'く', katakana: 'ク', roomaji: 'ku', chinese: '久' },
  { hiragana: 'け', katakana: 'ケ', roomaji: 'ke', chinese: '計' },
  { hiragana: 'こ', katakana: 'コ', roomaji: 'ko', chinese: '己' },
  { hiragana: 'さ', katakana: 'サ', roomaji: 'sa', chinese: '左' },
  { hiragana: 'し', katakana: 'シ', roomaji: 'shi', chinese: '之' },
  { hiragana: 'す', katakana: 'ス', roomaji: 'su', chinese: '寸' },
  { hiragana: 'せ', katakana: 'セ', roomaji: 'se', chinese: '世' },
  { hiragana: 'そ', katakana: 'ソ', roomaji: 'so', chinese: '曾' },
  { hiragana: 'た', katakana: 'タ', roomaji: 'ta', chinese: '太' },
  { hiragana: 'ち', katakana: 'チ', roomaji: 'chi', chinese: '知' },
  { hiragana: 'つ', katakana: 'ツ', roomaji: 'tsu', chinese: '川' },
  { hiragana: 'て', katakana: 'テ', roomaji: 'te', chinese: '天' },
  { hiragana: 'と', katakana: 'ト', roomaji: 'to', chinese: '止' },
  { hiragana: 'な', katakana: 'ナ', roomaji: 'na', chinese: '奈' },
  { hiragana: 'に', katakana: 'ニ', roomaji: 'ni', chinese: '仁' },
  { hiragana: 'ぬ', katakana: 'ヌ', roomaji: 'nu', chinese: '奴' },
  { hiragana: 'ね', katakana: 'ネ', roomaji: 'ne', chinese: '祢' },
  { hiragana: 'の', katakana: 'ノ', roomaji: 'no', chinese: '乃' },
  { hiragana: 'は', katakana: 'ハ', roomaji: 'ha', chinese: '波' },
  { hiragana: 'ひ', katakana: 'ヒ', roomaji: 'hi', chinese: '比' },
  { hiragana: 'ふ', katakana: 'フ', roomaji: 'fu', chinese: '不' },
  { hiragana: 'へ', katakana: 'ヘ', roomaji: 'he', chinese: '部' },
  { hiragana: 'ほ', katakana: 'ホ', roomaji: 'ho', chinese: '保' },
  { hiragana: 'ま', katakana: 'マ', roomaji: 'ma', chinese: '末' },
  { hiragana: 'み', katakana: 'ミ', roomaji: 'mi', chinese: '美' },
  { hiragana: 'む', katakana: 'ム', roomaji: 'mu', chinese: '武' },
  { hiragana: 'め', katakana: 'メ', roomaji: 'me', chinese: '女' },
  { hiragana: 'も', katakana: 'モ', roomaji: 'mo', chinese: '毛' },
  { hiragana: 'や', katakana: 'ヤ', roomaji: 'ya', chinese: '也' },
  { hiragana: '', katakana: '', roomaji: '' },
  { hiragana: 'ゆ', katakana: 'ユ', roomaji: 'yu', chinese: '由' },
  { hiragana: '', katakana: '', roomaji: '' },
  { hiragana: 'よ', katakana: 'ヨ', roomaji: 'yo', chinese: '与' },
  { hiragana: 'ら', katakana: 'ラ', roomaji: 'ra', chinese: '良' },
  { hiragana: 'り', katakana: 'リ', roomaji: 'ri', chinese: '利' },
  { hiragana: 'る', katakana: 'ル', roomaji: 'ru', chinese: '留' },
  { hiragana: 'れ', katakana: 'レ', roomaji: 're', chinese: '礼' },
  { hiragana: 'ろ', katakana: 'ロ', roomaji: 'ro', chinese: '吕' },
  { hiragana: 'わ', katakana: 'ワ', roomaji: 'wa', chinese: '和' },
  { hiragana: '', katakana: '', roomaji: '' },
  { hiragana: '', katakana: '', roomaji: '' },
  { hiragana: '', katakana: '', roomaji: '' },
  { hiragana: 'を', katakana: 'ヲ', roomaji: 'o', chinese: '遠' },
  { hiragana: 'ん', katakana: 'ン', roomaji: 'n', chinese: '无' },
]
